import type { Metadata } from "next";
import Header from "@/components/header/header";
import '../styles/global.scss'
import '../styles/reset.scss'
import { PizzaService } from "@/services/pizzaService";



export const metadata: Metadata = {
  title: "Next Pizza",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pizzas = await PizzaService.fetchPizzas(); 
  return (
    <html lang="en">
      <head>
        <title>
           SimPizza
        </title>
      </head>
      <body className="container">
        <Header />
        {children}
      </body>
    </html>
  );
}
